"""
Static Columbo Protocol Counter-Inquiry Trap Prompts.

Pre-written adversarial inquiries ('Phantom Detail' & 'Administrative Dead-End' traps)
designed to disrupt the scammer's conversational dominance and induce hesitation
without requiring dynamic LLM inference.
"""

from typing import Dict, List, Optional

TRAP_PROMPTS: Dict[str, Dict[str, List[str]]] = {
    "DIGITAL_ARREST_POLICE": {
        "en": [
            "Please provide your belt badge number and dispatch station landline extension so I can verify with the state control room.",
            "What is the official High Court e-Filing diary number so my counsel can verify it on ecourts.gov.in?",
            "Which police station general diary (GD) entry number was registered for this warrant?",
        ],
        "hi": [
            "कृपया अपना बेल्ट बैज नंबर और पुलिस स्टेशन का लैंडलाइन नंबर बताएं, मैं कंट्रोल रूम से पुष्टि करूँगा।",
            "इस वारंट का ई-कोर्ट केस नंबर क्या है? मेरे वकील अभी कोर्ट पोर्टल पर चेक करेंगे।",
            "आप किस थाने से बोल रहे हैं और जीडी एंट्री नंबर क्या है?",
        ],
        "bn": [
            "দয়া করে আপনার পুলিশ ব্যাজ নম্বর এবং থানার ল্যান্ডলাইন নম্বর দিন, আমি কন্ট্রোল রুমে যাচাই করব।",
            "এই ওয়ারেন্টের অফিসিয়াল কোর্ট কেস ডায়েরি নম্বর কত? আমার আইনজীবী এখনই যাচাই করবেন।",
            "কোন থানা থেকে বলছেন এবং জেনারেল ডায়েরি (GD) নম্বর কত?",
        ],
    },
    "CHILD_CUSTODY_EXTORTION": {
        "en": [
            "What is the name of the school class teacher who signed the handover slip at reception?",
            "Which hospital police outpost was this accident logged with? I am calling the duty doctor now.",
            "Can you put my child on the line right now to state their birth date and section?",
        ],
        "hi": [
            "स्कूल के किस शिक्षक ने बच्चे को सौंपा? उनका नाम और सेक्शन बताएं।",
            "किस अस्पताल की पुलिस चौकी में यह केस दर्ज हुआ है? मैं डॉक्टर से सीधे बात करता हूँ।",
            "तुरंत बच्चे से बात करवाएं और उसकी जन्मतिथि बताएं।",
        ],
        "bn": [
            "স্কুলের কোন শিক্ষক বাচ্চাকে আপনার হাতে তুলে দিয়েছেন? তার নাম বলুন।",
            "কোন হাসপাতালের পুলিশ ফাঁড়িতে এই দুর্ঘটনা নথিভুক্ত হয়েছে?",
            "এখনই বাচ্চার সাথে কথা বলুন এবং তার জন্ম তারিখ জানান।",
        ],
    },
    "ELECTRICITY_CUTOFF": {
        "en": [
            "What is the 10-digit consumer CA number and billing division code on your terminal?",
            "Which sub-division executive engineer authorized this disconnection notice?",
        ],
        "hi": [
            "आपके सिस्टम में मेरा 10 अंकों का उपभोक्ता सीए (CA) नंबर और सब-डिवीजन क्या दिख रहा है?",
            "किस बिजली सब-डिवीजन से यह नोटिस जारी हुआ है?",
        ],
        "bn": [
            "আপনার টার্মিনালে আমার ১০ সংখ্যার গ্রাহক সিএ (CA) নম্বর কত দেখাচ্ছে?",
            "কোন বিদ্যুৎ সাব-ডিভিশন থেকে এই লাইন কাটার নির্দেশ এসেছে?",
        ],
    },
    "KYC_ACCOUNT_FREEZE": {
        "en": [
            "What is my home branch IFSC code and the ticket number generated by the bank core banking system?",
            "I will visit my home branch in person. Give me the internal employee ID of the reviewing officer.",
        ],
        "hi": [
            "मेरी होम ब्रांच का आईएफएससी (IFSC) कोड और इस केस का बैंक टिकट नंबर क्या है?",
            "मैं बैंक शाखा जाकर पुष्टि करूंगा। अपने समीक्षा अधिकारी की कर्मचारी आईडी बताएं।",
        ],
        "bn": [
            "আমার হোম ব্রাঞ্চের IFSC কোড এবং ব্যাংকের অফিসিয়াল টিকিট নম্বর কত?",
            "আমি সরাসরি ব্রাঞ্চে যাচ্ছি। দায়িত্বপ্রাপ্ত অফিসারের এমপ্লয়ী আইডি দিন।",
        ],
    },
    "CUSTOMS_PARCEL_SEIZURE": {
        "en": [
            "What is the 13-character International Air Waybill (AWB) number and customs entry bill number?",
            "Which airport customs commissionerate seized this parcel? I will verify with the customs helpdesk.",
        ],
        "hi": [
            "इस पार्सल का 13 अंकों का एयर वेबिल (AWB) नंबर और कस्टम एंट्री नंबर क्या है?",
            "किस एयरपोर्ट कस्टम कमिश्नरेट ने यह पार्सल रोका है?",
        ],
        "bn": [
            "এই পার্সেলের ১৩ সংখ্যার এয়ার ওয়েবিল (AWB) নম্বর এবং কাস্টমস এন্ট্রি নম্বর কত?",
            "কোন বিমানবন্দর কাস্টমস বিভাগ এই পার্সেল আটকেছে?",
        ],
    },
}


def get_trap_prompt(category: str, language: str = "en") -> Optional[str]:
    """
    Retrieves the primary static trap prompt for a given scam category and language.

    Args:
        category: Taxonomy string (e.g. 'DIGITAL_ARREST_POLICE', 'CHILD_CUSTODY_EXTORTION').
        language: Language code ('en', 'hi', 'bn'). Defaults to 'en'.

    Returns:
        String prompt to display on the user's HUD or synthesize, or None if category not found.
    """
    category_prompts = TRAP_PROMPTS.get(category)
    if not category_prompts:
        return None

    lang_prompts = category_prompts.get(language) or category_prompts.get("en")
    if lang_prompts and len(lang_prompts) > 0:
        return lang_prompts[0]

    return None
