"""initial schema

Revision ID: 0cf5eef39efd
Revises: 
Create Date: 2026-08-15 13:17:36.538222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf5eef39efd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk_profile', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_hash', name='uq_device_user_hash')
    )
    op.create_index(op.f('ix_devices_device_hash'), 'devices', ['device_hash'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipient_hash', name='uq_recipient_user_hash')
    )
    op.create_index(op.f('ix_recipients_recipient_hash'), 'recipients', ['recipient_hash'], unique=False)
    op.create_index(op.f('ix_recipients_user_id'), 'recipients', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ALLOWED', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'CANCELLED', 'REPORTED', name='transactionstatus', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_id'), 'transactions', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('fraud_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'CONFIRMED_FRAUD', 'FALSE_POSITIVE', 'CLOSED', name='fraudcasestatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_cases_transaction_id'), 'fraud_cases', ['transaction_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('output_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_transaction_id'), 'model_predictions', ['transaction_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('device_score', sa.Float(), nullable=True),
    sa.Column('behaviour_score', sa.Float(), nullable=True),
    sa.Column('voice_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'WARN', 'CONFIRM_OR_CANCEL', name='riskdecision', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_created_at'), 'risk_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_transaction_id'), 'risk_scores', ['transaction_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_decision', sa.Enum('CONFIRM', 'CANCEL', 'REPORT', name='userdecision', native_enum=False, length=16), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_user_feedback_transaction')
    )
    op.create_index(op.f('ix_user_feedback_transaction_id'), 'user_feedback', ['transaction_id'], unique=False)
    op.create_table('voice_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('transcript_hash', sa.String(length=64), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('financial_request_score', sa.Float(), nullable=False),
    sa.Column('coercion_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_analysis_transaction_id'), 'voice_analysis', ['transaction_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='alertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_risk_score_id'), 'alerts', ['risk_score_id'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('factor_type', sa.String(length=50), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_risk_score_id'), 'risk_factors', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_factors_risk_score_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_score_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_voice_analysis_transaction_id'), table_name='voice_analysis')
    op.drop_table('voice_analysis')
    op.drop_index(op.f('ix_user_feedback_transaction_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_risk_scores_transaction_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_created_at'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_model_predictions_transaction_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_fraud_cases_transaction_id'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_recipients_user_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_recipient_hash'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
