"""add user financial profile tables

Revision ID: 2a01b580941b
Revises: e1d2c3b4a5f6
Create Date: 2026-09-09 20:19:20.894123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a01b580941b'
down_revision: Union[str, Sequence[str], None] = 'e1d2c3b4a5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_ledger_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_ledger_transactions_dedup_hash'), 'statement_ledger_transactions', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_statement_ledger_transactions_user_id'), 'statement_ledger_transactions', ['user_id'], unique=False)
    op.create_table('user_model_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_artifacts_is_active'), 'user_model_artifacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_model_artifacts_user_id'), 'user_model_artifacts', ['user_id'], unique=False)
    op.create_table('user_financial_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.Enum('STUDENT', 'SALARIED', 'HOMEMAKER', 'BUSINESS', 'RETIRED_ELDERLY', 'GIG_WORKER', 'FARMER_RURAL', 'GENERAL', name='userpersonaarchetype', native_enum=False, length=32), nullable=False),
    sa.Column('p50_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p90_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('p99_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_transactions_at_last_train', sa.Integer(), nullable=False),
    sa.Column('pending_transactions_count', sa.Integer(), nullable=False),
    sa.Column('last_retrained_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('needs_retrain', sa.Boolean(), nullable=False),
    sa.Column('active_artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_artifact_id'], ['user_model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_financial_profiles_last_active_at'), 'user_financial_profiles', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_user_financial_profiles_needs_retrain'), 'user_financial_profiles', ['needs_retrain'], unique=False)
    op.create_index(op.f('ix_user_financial_profiles_user_id'), 'user_financial_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed a foreign key on trusted_contacts and
    # dropping two unique constraints (trusted_device_bindings, user_sessions)
    # — pre-existing SQLite constraint-naming drift unrelated to this
    # migration's actual purpose (adding the three tables above). Deliberately
    # excluded so this migration only does what its message says.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_financial_profiles_user_id'), table_name='user_financial_profiles')
    op.drop_index(op.f('ix_user_financial_profiles_needs_retrain'), table_name='user_financial_profiles')
    op.drop_index(op.f('ix_user_financial_profiles_last_active_at'), table_name='user_financial_profiles')
    op.drop_table('user_financial_profiles')
    op.drop_index(op.f('ix_user_model_artifacts_user_id'), table_name='user_model_artifacts')
    op.drop_index(op.f('ix_user_model_artifacts_is_active'), table_name='user_model_artifacts')
    op.drop_table('user_model_artifacts')
    op.drop_index(op.f('ix_statement_ledger_transactions_user_id'), table_name='statement_ledger_transactions')
    op.drop_index(op.f('ix_statement_ledger_transactions_dedup_hash'), table_name='statement_ledger_transactions')
    op.drop_table('statement_ledger_transactions')
    # ### end Alembic commands ###
