"""contact info and device metadata

Revision ID: 62c167040c8b
Revises: 7a1b2c3d4e5f
Create Date: 2026-08-30 18:12:55.390378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c167040c8b'
down_revision: Union[str, Sequence[str], None] = '7a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contact_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_encrypted', sa.String(length=512), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_contact_info_user_id'), 'user_contact_info', ['user_id'], unique=True)
    op.add_column('devices', sa.Column('device_name', sa.String(length=120), nullable=True))
    op.add_column('devices', sa.Column('device_type', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    op.drop_column('devices', 'device_name')
    op.drop_index(op.f('ix_user_contact_info_user_id'), table_name='user_contact_info')
    op.drop_table('user_contact_info')
    # ### end Alembic commands ###
