import httpx
from datetime import datetime, timezone
from urllib.parse import parse_qs, urlparse

BASE_URL = "http://127.0.0.1:8000"
client = httpx.Client()

def test_complete_upi_handoff_and_guardian_flow():
    print("==================================================")
    print("STARTING E2E VERIFICATION OF UPI HANDOFF & RETURN FLOW")
    print("==================================================")

    suffix = str(int(datetime.now(timezone.utc).timestamp()))[-5:]
    
    # 1. Setup Payer and Trusted Contact
    payer = client.post(f"{BASE_URL}/api/v1/users", json={"name": "Rohit Verma", "phone_number": f"+91-98711-{suffix}"}).json()
    payer_id = payer["id"]
    guardian = client.post(f"{BASE_URL}/api/v1/users", json={"name": "Anita Verma", "phone_number": f"+91-98722-{suffix}"}).json()
    guardian_id = guardian["id"]
    
    contact_res = client.post(
        f"{BASE_URL}/api/v1/guardian/trusted-contacts",
        json={
            "user_id": payer_id,
            "contact_name": "Anita Verma (Wife)",
            "phone_number": f"+91-98722-{suffix}",
            "relationship": "Spouse",
        },
    )
    contact_id = contact_res.json()["id"]
    print(f"[OK] Created Payer (ID {payer_id}) and Linked Guardian Contact (ID {contact_id})")

    # 2. Initiate High-Risk Payment
    txn = client.post(
        f"{BASE_URL}/api/v1/transactions",
        json={
            "user_id": payer_id,
            "recipient_identifier": "merchant.crypto@upi",
            "device_identifier": "device-rohit-pixel",
            "amount": "85000.00",
        },
    ).json()
    txn_id = txn["id"]
    print(f"[OK] Created High-Risk Transaction {txn_id} for INR 85,000.00")

    # 3. Security Verification: Biometric Authorization
    auth_res = client.post(f"{BASE_URL}/api/v1/transactions/{txn_id}/authorize", json={"method": "BIOMETRIC"})
    assert auth_res.status_code == 200
    print("[OK] Biometric identity authorization verified")

    # 4. Trigger Guardian Approval Request (120s timer)
    req = client.post(f"{BASE_URL}/api/v1/guardian/requests", json={"transaction_id": txn_id, "trusted_contact_id": contact_id}).json()
    req_id = req["id"]
    assert req["outcome"] == "PENDING"
    assert req["remaining_seconds"] in (119, 120)
    print(f"[OK] Triggered Guardian Request {req_id} (Authoritative countdown: {req['remaining_seconds']}s)")

    # 5. Verify: Direct Confirmation is BLOCKED while Guardian Pending
    unauth_confirm = client.post(f"{BASE_URL}/api/v1/transactions/{txn_id}/confirm")
    assert unauth_confirm.status_code in (400, 403), f"Expected blocked confirm, got {unauth_confirm.status_code}"
    print("[OK] Verified transaction cannot be confirmed while Guardian Pending")

    # 6. Guardian Approves the Transaction
    appr_res = client.post(f"{BASE_URL}/api/v1/guardian/requests/{req_id}/approve", json={"notes": "Approved by spouse Anita"})
    assert appr_res.status_code == 200
    assert appr_res.json()["outcome"] == "APPROVED"
    print("[OK] Guardian approved the payment hold")

    # 7. Verify Transaction is in GUARDIAN_APPROVED State (Ready for UPI Handoff)
    txn_after_appr = client.get(f"{BASE_URL}/api/v1/transactions/{txn_id}").json()
    assert txn_after_appr["status"] == "GUARDIAN_APPROVED"
    print(f"[OK] Transaction state updated to: {txn_after_appr['status']} (Ready for PROCEED TO PAY)")

    # 8. UPI Payment Handoff: Verify Payload Construction
    # Simulating the exact parameters generated by PaymentAppLauncherService.buildUpiUri
    payee_upi = "merchantcrypto@upi"
    payee_name = "Apex Merchant"
    amount = "85000.00"
    txn_ref = f"TXN-{txn_id}"
    txn_note = f"AVARAN Protected Transfer - Ref TXN-{txn_id}"
    
    upi_uri = f"tez://upi/pay?pa={payee_upi}&pn={payee_name}&am={amount}&cu=INR&tn={txn_note}&tr={txn_ref}"
    parsed = parse_qs(urlparse(upi_uri).query)
    assert parsed["pa"][0] == payee_upi
    assert parsed["pn"][0] == payee_name
    assert parsed["am"][0] == amount
    assert parsed["cu"][0] == "INR"
    assert parsed["tr"][0] == txn_ref
    print("[OK] UPI deep-link URI constructed with full prefilled parameters (pa, pn, am, cu, tn, tr)")

    # 9. Verify Non-Terminal Handoff: Transaction is NOT completed when user merely opens UPI app
    check_in_progress = client.get(f"{BASE_URL}/api/v1/transactions/{txn_id}").json()
    assert check_in_progress["status"] == "GUARDIAN_APPROVED"
    print(f"[OK] Verified transaction remains in non-terminal state during external app handoff: {check_in_progress['status']}")

    # 10. External UPI App Reports Payment Success -> Complete Payment
    confirm_res = client.post(f"{BASE_URL}/api/v1/transactions/{txn_id}/confirm")
    assert confirm_res.status_code == 200
    assert confirm_res.json()["status"] == "CONFIRMED"
    print("[OK] Successfully confirmed payment after return from external UPI app")

    # 11. Database Persistence Verification
    db_final = client.get(f"{BASE_URL}/api/v1/transactions/{txn_id}").json()
    assert db_final["status"] == "CONFIRMED"
    print(f"[OK] Transaction permanently persisted in DB as: {db_final['status']}")

    # 12. Duplicate Payment Prevention Verification
    dup_attempt = client.post(f"{BASE_URL}/api/v1/transactions/{txn_id}/confirm")
    assert dup_attempt.status_code == 400
    print(f"[OK] Duplicate payment attempt rejected: {dup_attempt.json()['detail']}")

    print("\n==================================================")
    print("ALL UPI HANDOFF & RETURN FLOW CHECKS PASSED!")
    print("==================================================")

if __name__ == "__main__":
    test_complete_upi_handoff_and_guardian_flow()
