"""
S40 dataset registry.

Single source of truth for what each dataset is, where it legally came
from, whether we are allowed to use it, and whether it is present locally.

Verification status recorded here reflects what was actually checked from
authoritative sources on 2026-08-15 — see docs/DATA_STRATEGY.md for the
evidence trail. Nothing here is aspirational: a dataset that could not be
verified is marked PENDING and must not be downloaded (Phase 3 brief).

Local paths are resolved from the S40_DATA_DIR environment variable and
never hardcoded to a personal absolute path. Nothing in this module
downloads anything.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass
from enum import Enum
from pathlib import Path

#: Default root for locally-acquired datasets, relative to the repo.
#: Overridable via S40_DATA_DIR. The directory is git-ignored.
DEFAULT_DATA_DIR = Path(__file__).resolve().parents[2] / "ml" / "data" / "raw"


class VerificationStatus(str, Enum):
    #: Licence and provenance confirmed from an authoritative source.
    VERIFIED = "VERIFIED"
    #: Provenance confirmed, licence text could not be read programmatically.
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    #: Not yet confirmed. MUST NOT be downloaded until it is.
    PENDING = "PENDING"


class DownloadStatus(str, Enum):
    NOT_DOWNLOADED = "NOT_DOWNLOADED"
    PRESENT = "PRESENT"


class Task(str, Enum):
    TRANSACTION_FRAUD = "TRANSACTION_FRAUD"
    ANOMALY_VALIDATION = "ANOMALY_VALIDATION"
    VOICE_SOCIAL_ENGINEERING = "VOICE_SOCIAL_ENGINEERING"
    SCENARIO_TESTING = "SCENARIO_TESTING"


@dataclass(frozen=True)
class DatasetEntry:
    name: str
    description: str
    #: Authoritative origin, not a mirror.
    source_url: str
    provenance: str
    licence: str
    licence_notes: str
    verification: VerificationStatus
    download: DownloadStatus
    #: Path fragment beneath the data dir. Never absolute.
    relative_path: str
    adapter: str
    target_field: str | None
    tasks: tuple[Task, ...]
    limitations: str
    #: True only if the source explicitly supports calling it real-world data.
    is_real_world_data: bool

    def local_path(self, data_dir: Path | None = None) -> Path:
        root = Path(data_dir) if data_dir else data_dir_from_env()
        return root / self.relative_path

    def is_present(self, data_dir: Path | None = None) -> bool:
        return self.local_path(data_dir).exists()


def data_dir_from_env() -> Path:
    configured = os.environ.get("S40_DATA_DIR")
    return Path(configured) if configured else DEFAULT_DATA_DIR


REGISTRY: dict[str, DatasetEntry] = {
    "paysim": DatasetEntry(
        name="paysim",
        description=(
            "Synthetic mobile-money transactions with injected fraud, from the "
            "PaySim agent-based simulator."
        ),
        source_url="https://www.kaggle.com/datasets/ealaxi/paysim1",
        provenance=(
            "Generated by the PaySim simulator (Dr. Edgar Lopez-Rojas; "
            "'PaySim: A financial mobile money simulator for fraud detection', "
            "EMSS 2016). The simulator is seeded from AGGREGATED logs of a real "
            "mobile-money service in an African country; the published rows are "
            "simulator output, not real customer records."
        ),
        licence="Simulator: GPL-3.0. Kaggle distribution: not machine-readable.",
        licence_notes=(
            "GPL-3.0 on the simulator source was confirmed from the author's "
            "GitHub repository. The licence attached to the Kaggle CSV could NOT "
            "be read programmatically (Kaggle serves a JavaScript app, so the "
            "licence field is not in the fetched HTML). Widely cited as CC BY-SA "
            "4.0, but that is unconfirmed here and must be checked by a human on "
            "the dataset page before any public submission. The project owner "
            "has explicitly authorized local use of this file for internal "
            "prototype work (2026-09-04) — this does NOT resolve the "
            "public-redistribution question above."
        ),
        verification=VerificationStatus.PARTIALLY_VERIFIED,
        download=DownloadStatus.PRESENT,
        relative_path="paysim/PS_20174392719_1491204439457_log.csv",
        adapter="ml.data.adapters.paysim_adapter.PaySimAdapter",
        target_field="isFraud",
        tasks=(Task.TRANSACTION_FRAUD,),
        limitations=(
            "Synthetic. Fraud appears only in TRANSFER/CASH_OUT. No device, no "
            "geography, no wall-clock time. ~0.13% positive."
        ),
        is_real_world_data=False,
    ),
    "ieee_cis": DatasetEntry(
        name="ieee_cis",
        description="Vesta e-commerce transactions with identity/device features.",
        source_url="https://www.kaggle.com/competitions/ieee-fraud-detection",
        provenance=(
            "Vesta Corporation real-world e-commerce transactions, released for "
            "the IEEE-CIS Fraud Detection competition (2019), organised with the "
            "IEEE Computational Intelligence Society."
        ),
        licence="Kaggle competition rules — NOT VERIFIED.",
        licence_notes=(
            "The competition rules page could not be read programmatically "
            "(JavaScript app). Kaggle competition data is commonly restricted to "
            "competition/non-commercial use with redistribution prohibited, and "
            "typically requires accepting the rules while signed in. Because the "
            "terms are unconfirmed AND this is real customer data, this dataset "
            "was NOT downloaded by this project's governed acquisition path, and "
            "`download` below is deliberately left NOT_DOWNLOADED — flipping it "
            "to PRESENT while `verification` stays PENDING would defeat the "
            "safety invariant ml/tests/test_canonical_and_registry.py checks for "
            "(PRESENT implying a verified/safe-to-use dataset). The project owner "
            "has separately provided the raw files directly and explicitly "
            "authorized LOCAL, READ-ONLY use for EDA and evaluation-only "
            "generalization checks in this one retraining pass (2026-09-04) — "
            "recorded here in prose, not in the structured status fields, "
            "because that authorization is exceptional and does not resolve the "
            "underlying Kaggle licence question above. This dataset must not be "
            "pooled into any training target (ml/datasets/preparation.py already "
            "refuses this — see MODEL_DATASET_MAPPING) or redistributed."
        ),
        verification=VerificationStatus.PENDING,
        download=DownloadStatus.NOT_DOWNLOADED,
        relative_path="ieee_cis/train_transaction.csv",
        adapter="ml.data.adapters.ieee_cis_adapter.IeeeCisAdapter",
        target_field="isFraud",
        tasks=(Task.TRANSACTION_FRAUD,),
        limitations=(
            "Card-not-present e-commerce fraud, a different mechanism from S40's "
            "socially-engineered payments. Chargeback-derived labels. Most "
            "features anonymized. Identity file covers only part of transactions."
        ),
        is_real_world_data=True,
    ),
    "indian_online_scam": DatasetEntry(
        name="indian_online_scam",
        description=(
            "Indian card/online payment fraud transactions with fraud-type "
            "categories (phishing, scam, identity theft, malware, payment card "
            "fraud)."
        ),
        source_url="provided directly by project owner — no public URL",
        provenance=(
            "Provided directly by the project owner (2026-09-04), not a public "
            "download — no source URL to record. See docs/EDA_REPORT.md for the "
            "full measurement this entry is based on."
        ),
        licence="Unknown — provided directly, no licence metadata available.",
        licence_notes=(
            "No licence text accompanies this file. Used here only under the "
            "project owner's own authorization for internal prototype work; "
            "must not be redistributed or used outside this project without "
            "the owner separately confirming its terms."
        ),
        verification=VerificationStatus.PARTIALLY_VERIFIED,
        download=DownloadStatus.PRESENT,
        relative_path="indian_scam/transactions.csv",
        adapter="ml.data.adapters.indian_scam_adapter.IndianScamAdapter",
        target_field="is_fraudulent",
        tasks=(Task.TRANSACTION_FRAUD, Task.ANOMALY_VALIDATION),
        limitations=(
            "The raw file is a ~4x self-concatenation (6,753 of 7,953 rows are "
            "exact duplicates of a ~1,200-row export) — the adapter deduplicates "
            "before use. Once deduplicated, customers do not repeat (1,132 "
            "unique customers / 1,200 rows), so it cannot support S40's original "
            "per-user behavioural feature design — used with the recipient-"
            "centric feature set instead (merchants do repeat: 100 merchants / "
            "1,200 rows). fraud_type categories are nearly evenly split at an "
            "overall 31% fraud rate, far above any organically-observed rate — "
            "the signature of a constructed/practice dataset, documented as such "
            "rather than presented as organic real-world logs."
        ),
        is_real_world_data=False,
    ),
    "credit_card_ulb": DatasetEntry(
        name="credit_card_ulb",
        description="European credit-card transactions, PCA-anonymized, 2 days.",
        source_url="https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud",
        provenance=(
            "Collected during a research collaboration between Worldline and the "
            "Machine Learning Group, Université Libre de Bruxelles. Cite: Dal "
            "Pozzolo, Caelen, Johnson & Bontempi, 'Calibrating Probability with "
            "Undersampling for Unbalanced Classification', IEEE CIDM 2015."
        ),
        licence="Database Contents License (DbCL) v1.0",
        licence_notes=(
            "DbCL v1.0 per the Kaggle hosting information; DbCL permits use, "
            "modification and redistribution with attribution. Real cardholder "
            "data, but V1..V28 are PCA components and no identifiers are "
            "published, so rows are not directly re-identifiable. NOT in the "
            "original S40 specification — added by the project owner in the "
            "Phase 3 brief."
        ),
        verification=VerificationStatus.VERIFIED,
        download=DownloadStatus.NOT_DOWNLOADED,
        relative_path="credit_card_ulb/creditcard.csv",
        adapter="ml.data.adapters.credit_card_adapter.CreditCardAdapter",
        target_field="Class",
        tasks=(Task.ANOMALY_VALIDATION,),
        limitations=(
            "No user/device/recipient identifiers, so no behavioural features are "
            "possible. PCA features are unexplainable. ~0.172% positive. 2013 "
            "European context, EUR amounts."
        ),
        is_real_world_data=True,
    ),
    "teleantifraud": DatasetEntry(
        name="teleantifraud",
        description="Chinese telecom fraud speech-text corpus (~28.5k pairs, ~307h).",
        source_url="https://huggingface.co/datasets/JimmyMa99/TeleAntiFraud",
        provenance=(
            "Assembled by Zhiming Ma (2025). Hybrid construction: ASR-transcribed "
            "anonymized real call recordings, TTS regeneration for privacy, and "
            "multi-agent adversarial synthesis for emerging fraud tactics."
        ),
        licence="Apache License 2.0",
        licence_notes=(
            "Apache-2.0 confirmed from the Hugging Face dataset card (copyright "
            "Zhiming Ma, 2025). Permits commercial and hackathon use with "
            "attribution and licence notice."
        ),
        verification=VerificationStatus.VERIFIED,
        download=DownloadStatus.NOT_DOWNLOADED,
        relative_path="teleantifraud/train.jsonl",
        adapter="ml.data.adapters.teleantifraud_adapter.TeleAntiFraudAdapter",
        target_field="label",
        tasks=(Task.VOICE_SOCIAL_ENGINEERING,),
        limitations=(
            "CHINESE LANGUAGE — S40 is India-first (English/Hindi/Hinglish). The "
            "social-engineering taxonomy transfers; trained text classifiers and "
            "their metrics do not. Audio is partly synthetic. ~307h of audio makes "
            "this a large download. See docs/DATA_STRATEGY.md open question."
        ),
        is_real_world_data=False,
    ),
    "s40_synthetic": DatasetEntry(
        name="s40_synthetic",
        description="S40's own deterministic scenario generator (India/UPI framing).",
        source_url="ml/data/generators/synthetic_generator.py",
        provenance="Generated in-repo. No external data, no real people.",
        licence="Project-owned.",
        licence_notes="No third-party licence applies.",
        verification=VerificationStatus.VERIFIED,
        download=DownloadStatus.PRESENT,  # generated on demand, always available
        relative_path="",
        adapter="ml.data.adapters.synthetic_adapter.SyntheticAdapter",
        target_field="is_fraud",
        tasks=(Task.SCENARIO_TESTING, Task.TRANSACTION_FRAUD),
        limitations=(
            "Synthetic. Never evidence of real-world accuracy; never to be "
            "described as representing real Indian banking behaviour."
        ),
        is_real_world_data=False,
    ),
}


def get(name: str) -> DatasetEntry:
    if name not in REGISTRY:
        raise KeyError(f"Unknown dataset '{name}'. Known: {sorted(REGISTRY)}")
    return REGISTRY[name]


def for_task(task: Task) -> list[DatasetEntry]:
    return [entry for entry in REGISTRY.values() if task in entry.tasks]


def downloadable() -> list[DatasetEntry]:
    """Datasets whose licence status permits acquisition.

    PENDING entries are excluded by design: the Phase 3 brief forbids
    downloading anything whose licensing is unclear.
    """
    return [
        entry
        for entry in REGISTRY.values()
        if entry.verification is not VerificationStatus.PENDING and entry.relative_path
    ]


def manifest() -> dict:
    """Serializable snapshot. Safe to commit — contains no data, no secrets."""
    return {
        "generated_by": "ml/data/registry.py",
        "datasets": {
            name: {
                **asdict(entry),
                "verification": entry.verification.value,
                "download": entry.download.value,
                "tasks": [t.value for t in entry.tasks],
            }
            for name, entry in REGISTRY.items()
        },
    }


def write_manifest(path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest(), indent=2), encoding="utf-8")
    return path
