"""
S40 transaction fraud model — the single training entry point.

    python -m ml.training.train_fraud

One command runs the whole pipeline: build data -> validate -> baseline ->
search -> train -> calibrate -> select threshold -> evaluate ONCE on test
-> save a versioned artifact -> register it.

THE TEST SET IS TOUCHED EXACTLY ONCE, at the very end, after every choice
has been made on validation (Critical Rule #5). The code is arranged so
this is structurally evident: `test` does not appear anywhere above
`_final_test_evaluation`.

Flags:
    --users N          synthetic users to generate
    --no-search        skip the hyperparameter search (use config defaults)
    --experimental     register as experimental instead of promoting
    --output DIR       artifact root (default ml/models/fraud)
"""

from __future__ import annotations

import argparse
import json
import time
import warnings
from pathlib import Path

from ml.data.generators import SyntheticConfig
from ml.registry.artifact import build_metadata, new_version, save_artifact
from ml.registry.model_registry import ModelRegistry
from ml.training.baseline import train_baseline
from ml.training.calibration import assess_calibration
from ml.training.config import TrainingConfig, XGBParams
from ml.training.dataset import TrainingData, build_training_data
from ml.training.evaluate import (
    best_threshold_by_f1,
    evaluate,
    expected_calibration_error,
    threshold_sweep,
)
from ml.training.feature_manifest import manifest
from ml.training.search import params_from_trial, run_search
from ml.training.target import S40_FRAUD_TARGET
from ml.training.xgb_model import train_xgb

warnings.filterwarnings("ignore", category=FutureWarning)

#: Stated plainly in every artifact. These numbers describe synthetic data.
CAVEATS = (
    "PROTOTYPE — NOT A PRODUCTION BANKING FRAUD MODEL. Trained and evaluated "
    "ONLY on S40 synthetic data generated by ml/data/generators, because no "
    "public dataset was available under the project's data-governance rules "
    "(IEEE-CIS licence PENDING; PaySim and others require an authenticated "
    "manual download that has not been performed). Every metric here therefore "
    "measures the model's ability to recover patterns a generator deliberately "
    "put there. It is NOT evidence of real-world fraud-detection accuracy and "
    "must never be presented as such. Real performance is unmeasured."
)


def _log(message: str) -> None:
    print(message, flush=True)


def _final_test_evaluation(detector_probs, data: TrainingData, threshold: float) -> dict:
    """The one and only look at the test set."""
    result = evaluate(data.test.y, detector_probs, split="test", threshold=threshold)
    return {
        **result.to_dict(),
        "expected_calibration_error": expected_calibration_error(
            data.test.y, detector_probs
        ),
    }


def train(
    config: TrainingConfig | None = None,
    *,
    run_hyperparameter_search: bool = True,
    output_root: Path | None = None,
    promote: bool = True,
) -> dict:
    config = config or TrainingConfig()
    started = time.perf_counter()

    # -- 1. data ---------------------------------------------------------
    _log("[1/8] Building leakage-safe training data…")
    data = build_training_data(config)
    for name, split in data.as_dict().items():
        dist = split.distribution()
        _log(
            f"      {name:11} rows={dist['rows']:6d} positives={dist['positives']:5d} "
            f"rate={dist['positive_rate']:.4f}"
        )

    # -- 2. baseline -----------------------------------------------------
    _log("[2/8] Training logistic-regression baseline…")
    baseline = train_baseline(data.train.X, data.train.y, seed=config.seed)
    baseline_val = evaluate(
        data.validation.y, baseline.predict_proba(data.validation.X), split="validation"
    )
    _log(f"      baseline validation PR-AUC={baseline_val.pr_auc:.4f}")

    # -- 3. hyperparameter search (validation only) ----------------------
    if run_hyperparameter_search:
        _log("[3/8] Hyperparameter search (validation only)…")
        search = run_search(
            data.train.X, data.train.y, data.validation.X, data.validation.y, config=config
        )
        params = params_from_trial(search.best)
        search_record = search.to_dict()
        _log(
            f"      {len(search.trials)} trials; selected '{search.best.name}' "
            f"PR-AUC={search.best.validation_pr_auc:.4f}"
        )
    else:
        params = config.xgb
        search_record = {"skipped": True}
        _log("[3/8] Hyperparameter search skipped.")

    # -- 4. final model --------------------------------------------------
    _log("[4/8] Training XGBoost with the selected configuration…")
    train_started = time.perf_counter()
    model = train_xgb(
        data.train.X,
        data.train.y,
        data.validation.X,
        data.validation.y,
        config=config,
        params=params,
    )
    train_seconds = time.perf_counter() - train_started
    raw_validation = model.predict_proba(data.validation.X)
    xgb_val = evaluate(data.validation.y, raw_validation, split="validation")
    _log(
        f"      trained in {train_seconds:.2f}s (best_iteration={model.best_iteration}); "
        f"validation PR-AUC={xgb_val.pr_auc:.4f}"
    )

    # -- 5. calibration (validation only) --------------------------------
    _log("[5/8] Assessing probability calibration…")
    calibrator, calibration_report = assess_calibration(data.validation.y, raw_validation)
    _log(f"      {calibration_report.rationale.splitlines()[0]}")

    calibrated_validation = (
        calibrator.transform(raw_validation) if calibrator else raw_validation
    )

    # -- 6. threshold selection (validation only) ------------------------
    _log("[6/8] Selecting operating threshold on validation…")
    sweep = threshold_sweep(data.validation.y, calibrated_validation)
    chosen = best_threshold_by_f1(sweep)
    _log(
        f"      threshold={chosen.threshold:.2f} "
        f"precision={chosen.precision:.3f} recall={chosen.recall:.3f} F1={chosen.f1:.3f}"
    )

    # -- 7. FINAL TEST EVALUATION (first and only touch) -----------------
    _log("[7/8] Final evaluation on the held-out test set (first touch)…")
    raw_test = model.predict_proba(data.test.X)
    calibrated_test = calibrator.transform(raw_test) if calibrator else raw_test
    test_metrics = _final_test_evaluation(calibrated_test, data, chosen.threshold)
    raw_test_metrics = evaluate(
        data.test.y, raw_test, split="test_raw", threshold=chosen.threshold
    ).to_dict()
    _log(
        f"      test PR-AUC={test_metrics['pr_auc']:.4f} "
        f"ROC-AUC={test_metrics['roc_auc']:.4f} "
        f"precision={test_metrics['at_threshold']['precision']:.3f} "
        f"recall={test_metrics['at_threshold']['recall']:.3f}"
    )

    # -- 8. artifact + registry ------------------------------------------
    _log("[8/8] Saving versioned artifact…")
    metrics = {
        "baseline_validation": baseline_val.to_dict(),
        "baseline_coefficients": baseline.coefficients()[:10],
        "xgboost_validation_raw": xgb_val.to_dict(),
        "xgboost_validation_calibrated": evaluate(
            data.validation.y,
            calibrated_validation,
            split="validation_calibrated",
            threshold=chosen.threshold,
        ).to_dict(),
        "threshold_sweep_validation": [t.to_dict() for t in sweep],
        "test": test_metrics,
        "test_raw_uncalibrated": raw_test_metrics,
        "feature_importance_gain": model.feature_importance(),
        "training_seconds": train_seconds,
        "target": S40_FRAUD_TARGET.describe(),
    }

    version = new_version()
    metadata = build_metadata(
        model_name="s40_transaction_fraud",
        model_version=version,
        seed=config.seed,
        datasets=[config.dataset],
        dataset_notes=CAVEATS,
        split_report=data.split_report,
        training_config=config.to_dict(),
        hyperparameters=params.to_dict(),
        scale_pos_weight=model.scale_pos_weight,
        best_iteration=model.best_iteration,
        feature_manifest_version=manifest()["manifest_version"],
        feature_names=list(data.feature_names),
        metrics=metrics,
        hyperparameter_search=search_record,
        calibration=calibration_report.to_dict(),
        selected_threshold=chosen.threshold,
        caveats=CAVEATS,
    )

    path = save_artifact(
        model.booster, calibrator, metadata, manifest(), root=output_root
    )
    registry = ModelRegistry(root=output_root) if output_root else ModelRegistry()
    if promote:
        registry.promote(version)
        _log(f"      promoted {version} to current")
    else:
        registry.register_experimental(version)
        _log(f"      registered {version} as experimental")

    _log(f"      artifact: {path}")
    _log(f"Done in {time.perf_counter() - started:.1f}s")

    return {
        "version": version,
        "path": str(path),
        "validation_pr_auc": xgb_val.pr_auc,
        "baseline_validation_pr_auc": baseline_val.pr_auc,
        "test_metrics": test_metrics,
        "threshold": chosen.threshold,
        "calibrated": calibrator is not None,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the S40 transaction fraud model.")
    parser.add_argument("--users", type=int, default=800, help="synthetic users to generate")
    parser.add_argument("--seed", type=int, default=40)
    parser.add_argument("--no-search", action="store_true", help="skip hyperparameter search")
    parser.add_argument(
        "--experimental", action="store_true", help="register without promoting to current"
    )
    parser.add_argument("--output", type=Path, default=None, help="artifact root directory")
    args = parser.parse_args()

    config = TrainingConfig(
        seed=args.seed,
        synthetic=SyntheticConfig(seed=args.seed, users=args.users, history_per_user=25),
        xgb=XGBParams(),
    )
    summary = train(
        config,
        run_hyperparameter_search=not args.no_search,
        output_root=args.output,
        promote=not args.experimental,
    )
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
