"""
Adapter for S40's own synthetic data.

Unlike the external adapters this one has no licensing question and no
acquisition step — it calls the generator directly. It exists so that
synthetic data flows through exactly the same canonical/validation/split
machinery as public data, rather than taking a privileged shortcut.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from ml.data.adapters.base import AdapterResult, DatasetAdapter
from ml.data.canonical import (
    Availability,
    CanonicalColumn as C,
    FeatureAvailability,
    LabelDefinition,
)
from ml.data.generators.synthetic_generator import SyntheticConfig, SyntheticGenerator


class SyntheticAdapter(DatasetAdapter):
    name = "s40_synthetic"

    def __init__(self, config: SyntheticConfig | None = None) -> None:
        self.config = config or SyntheticConfig()

    def generate(self) -> AdapterResult:
        """Produce data without touching the filesystem."""
        frame = SyntheticGenerator(self.config).generate()
        return AdapterResult(
            frame=frame,
            availability=self.availability(),
            label=self.label_definition(),
        )

    def load(self, path: Path | None = None) -> AdapterResult:  # type: ignore[override]
        """Generated in-memory; `path` is accepted only for interface parity."""
        return self.generate()

    def read_raw(self, path: Path) -> pd.DataFrame:
        return pd.read_csv(path)

    def to_canonical(self, raw: pd.DataFrame) -> AdapterResult:
        return AdapterResult(
            frame=self.finalize(raw),
            availability=self.availability(),
            label=self.label_definition(),
        )

    def availability(self) -> FeatureAvailability:
        observed = (
            C.USER_ID.value,
            C.RECIPIENT_ID.value,
            C.DEVICE_ID.value,
            C.AMOUNT.value,
            C.TRANSACTION_TYPE.value,
            C.TIMESTAMP.value,
            C.TIME_INDEX.value,
            C.LOCATION.value,
            C.IS_FRAUD.value,
        )
        availability = {column: Availability.OBSERVED for column in observed}
        availability.update(
            {
                C.SOURCE_DATASET.value: Availability.DERIVED,
                C.SOURCE_ROW_ID.value: Availability.DERIVED,
                # Balances are not simulated: modelling realistic balance
                # dynamics is a research problem of its own, and inventing
                # them would be fabrication (spec §37).
                C.SENDER_BALANCE_BEFORE.value: Availability.ABSENT,
                C.SENDER_BALANCE_AFTER.value: Availability.ABSENT,
            }
        )
        return FeatureAvailability(
            dataset=self.name,
            availability=availability,
            notes={
                C.IS_FRAUD.value: (
                    "Scenario ground truth from the generator, not a model output "
                    "and not an observation of real fraud."
                ),
                C.SENDER_BALANCE_BEFORE.value: "Not simulated; never imputed.",
            },
        )

    def label_definition(self) -> LabelDefinition:
        return LabelDefinition(
            source_field="is_fraud",
            positive_meaning="Scenario constructed to represent fraudulent activity.",
            negative_meaning=(
                "Scenario constructed to represent legitimate activity — including "
                "deliberately suspicious-looking legitimate cases "
                "(FALSE_POSITIVE, LEGITIMATE_HIGH_VALUE, NEW_RECIPIENT)."
            ),
            s40_compatible=True,
            limitations=(
                "FULLY SYNTHETIC. Generated by ml/data/generators, not observed. "
                "Class balance is a design choice, not a measurement. Never usable "
                "as evidence of real-world accuracy and never to be described as "
                "representing real Indian banking behaviour."
            ),
        )
